# Generated by Django 2.0.3 on 2018-04-01 23:50

from django.db import migrations, models
import django.db.models.deletion
import panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=panel.models.StoryImage.get_story_image_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='images',
        ),
        migrations.AddField(
            model_name='storyimage',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Story'),
        ),
    ]
