# Generated by Django 2.0.3 on 2018-03-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='long',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
