# Generated by Django 2.0.3 on 2018-04-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20180401_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='storyimage',
            name='caption',
            field=models.TextField(null=True),
        ),
    ]
