# Generated by Django 2.0.3 on 2018-04-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20180419_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storyimage',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
